### ISSUE TITLE
404 on Vercel

### ISSUE THREAD

**Issue by EnchantedDonutStudioz** [amethystnetwork-dev/Rammerhead#1]
![Screenshot 2023-12-09 111924](https://github.com/amethystnetwork-dev/Rammerhead/assets/123824280/f23344f3-5365-4e47-91b6-fe03ec259d8a)
When I forked and deployed on Vercel, there is a 404 error. Help?

**Comment by rxfe-a** [comment]
Cause u deployed it like a static site with no build commands Not every proxy will automatically deploy like that

**Comment by Potato-constellation** [comment]
can you give me an example of one that isnt static

**Comment by pretzer25** [comment]
you can still deploy it, just a different way

**Comment by mdoryammilwalrus** [comment]
https://amethystnetwork-dev.github.io/docs/static-hosts/
